#注意 如果在记事本上编写，下面不要缩进使用tab，不然报错
spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.cloud.model  
  mapper-locations: classpath:mybatis/mapper/**/*.xml       
spring:
  profiles: dev #开发环境
  application:
    name: service-product-config #*************服务名***************
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8  # **************数据库连接地址***********************
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                
      initial-size: 5                            
      max-total: 5                               
      max-wait-millis: 150                       

eureka:
  client:
    registerWithEureka: true 
    fetchRegistry: true 
    serviceUrl: 
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} 
    prefer-ip-address: true 
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.cloud.model  
  mapper-locations: classpath:mybatis/mapper/**/*.xml      
spring:
  profiles: prod #生产环境
  application:
    name: service-product-config #*************服务名***************
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8  # **************数据库连接地址***********************
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                
      initial-size: 5                            
      max-total: 5                               
      max-wait-millis: 150                       

eureka:
  client:
    registerWithEureka: true 
    fetchRegistry: true 
    serviceUrl: 
      defaultZone: http://eureka6001.com:6001/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} 
    prefer-ip-address: true 
    
    
emp:
  name: zhangsan
 
    
    
    
    
#保存时注意， 选择UTF-8  保存